# Generated by Django 2.1.5 on 2019-04-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.IntegerField()),
                ('q_datetime', models.DateTimeField(auto_now_add=True)),
                ('q_result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleQuery',
            fields=[
                ('querylog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='query.QueryLog')),
                ('type', models.IntegerField()),
                ('target', models.CharField(max_length=200)),
            ],
            bases=('query.querylog',),
        ),
        migrations.CreateModel(
            name='SpecQuery1',
            fields=[
                ('querylog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='query.QueryLog')),
                ('proto', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
            ],
            bases=('query.querylog',),
        ),
        migrations.CreateModel(
            name='SpecQuery2',
            fields=[
                ('querylog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='query.QueryLog')),
                ('proto', models.CharField(max_length=20)),
                ('e_app', models.TextField()),
            ],
            bases=('query.querylog',),
        ),
        migrations.CreateModel(
            name='SpecQuery3',
            fields=[
                ('querylog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='query.QueryLog')),
                ('proto', models.CharField(max_length=20)),
                ('e_app', models.TextField()),
            ],
            bases=('query.querylog',),
        ),
    ]
